[package]
name = "git-clown"
version = "0.1.0"
authors = ["Hilmar Gústafsson"]
edition = "2018"
license = "MIT"
description = """
The maniacal git clone wrapper.
"""
repository = "https://github.com/lihram/git-clown-rs"
readme = "README.md"
keywords = ["git", "organize", "clone"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
url = "2.2.0"
argh = "0.1.4"
dirs = "3.0.1"

[[bin]]
name = "git-clown"
path = "src/git-clown.rs"
